spring.datasource.url=jdbc:postgresql://localhost:5432/grocerydb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.jpa.show-sql=true

logging.level.org.flywaydb=DEBUG

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=price-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer